# Global Vars
NUM_PROCS = 2
CACHE_SIZE = 1 #KB
MEMORY_SIZE = 32 #KB
BLOCK_SIZE = 32 #Bytes
DATABUS_WIDTH = 32 #bits
NUM_BLOCKS_MEMORY = 1024*MEMORY_SIZE/BLOCK_SIZE
NUM_BLOCKS_CACHE = 1024*CACHE_SIZE/BLOCK_SIZE

M = 0
O = 1
E = 2
S = 3
I = 4

NP = 5

#define NUM_ITER (1LL<<15)
