# Global Vars
NUM_RS=1
NUM_FU=2
NUM_TYPES_INSTR=9
MAX_REORDER_BUFFER=128
MAX_STORE_BUFFER=8 
MAX_RESERVATION_STATION=128
MAX_REGISTERS=8
MAX_INSTR=1

global_ins_counter = 0
store_counter = 0
global_time = 0
